apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c23qgssm4-python
  janus-idp.io/tekton: c23qgssm4-python
  backstage.io/kubernetes-id: c23qgssm4-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c23qgssm4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
